[package]
name = "pthread-3ds"
authors = [ "Andrea Ciliberti <meziu210@icloud.com>" ]
version = "0.1.0"
license = "MIT/Apache 2.0"
edition = "2021"

[dependencies]
libc = "0.2.116"
spin = { version = "0.9", default-features = false, features = ["rwlock", "std"] }